### ISSUE TITLE
Программа исполняется в один поток

### ISSUE THREAD

**Issue by vporoshok** [MishenkoAndrey/gotogo#1]
В текущей реализации программа исполняется в один поток

**Comment by MishenkoAndrey** [comment]
@vporoshok из задания не очень понятно. Могу ли я вычитать stdin а отдельную переменную?

**Comment by vporoshok** [comment]
в смысле целиком? Это будет удовлетворять постановке задачи, однако, будет очень неэкономным вычитывать все данные в оперативную память. Ну и проблема выполнения в один поток не от этого зависит

**Comment by vporoshok** [comment]
ничего не исправлено, запросы выполняются в один поток

<img width="1092" alt="Screenshot 2020-02-19 at 13 18 11" src="https://user-images.githubusercontent.com/5063912/74821016-63fdf980-531c-11ea-89ba-8788aba76306.png">

<img width="538" alt="Screenshot 2020-02-19 at 13 18 38" src="https://user-images.githubusercontent.com/5063912/74821038-6bbd9e00-531c-11ea-9ab2-bd562057b214.png">
